### ISSUE TITLE
Not rendering in nextjs

### ISSUE THREAD

**Issue by rodbs** [mifi/react-lottie-player#10]
Hi, and thanks for your plugin!!

I've created an animation that works in LottieFiles
https://lottiefiles.com/share/dzuigkaa#_=_

But I cannot get it to work in nextjs. It renders a white svg object.

Any ideas? Not sure if it's due to the way the json files are imported in nextjs ...

**Comment by mifi** [comment]
Do other animations work?

I'm using `react-lottie-player` in gatsby and it works for me (also SSR)

**Comment by rodbs** [comment]
I've got it to work.
It was because I'm using audio in my animation.

But now I'm getting another error.

According to this issue Lottie supports audio
https://github.com/airbnb/lottie-web/issues/231
https://github.com/airbnb/lottie-web/wiki/Audio

So in my case I've done:
```
import React, { useState } from 'react';
import Lottie from 'react-lottie-player';
import ReactHowler from 'react-howler';

import lottieJson from '../data/vowel/data.json';


const LottiePage = () => {

  function createAudio(assetPath) {
    return new Howl({
      src: [assetPath]
    });
  }

  return (
    <div>
      <Lottie
        loop
        animationData={lottieJson}
        style={{ width: 1280, height: 720 }}
        audioFactory={createAudio}
      />
    </div>
```

And it works (the animation playing the audio) but it raises this error (I guess because audioFactory prop is not implemented in react-lottie-player)

```
react-dom.development.js:67 Warning: React does not recognize the `audioFactory` prop on a DOM element. If you intentionally want it to appear in the DOM as a custom attribute, spell it as lowercase `audiofactory` instead. If you accidentally passed it from a parent component, remove it from the DOM element.
```

**Comment by mifi** [comment]
Ah, can you see if this is solved by adding audioFactory to propTypes:

https://github.com/mifi/react-lottie-player/blob/82976eb18017e3090befc4e6cefa26f24dec3a1a/src/index.js#L142

**Comment by rodbs** [comment]
Yes, it works adding audioFactory to propTypes and to the function

BTW, I'm also getting this error:
```
Warning: Failed prop type: The prop `animationData` is marked as required in `<<anonymous>>`, but its value is `undefined`.
```
I guess while the component is rerendering  animationData is undefined and it raises this error. I can control it by checking if variable is populated, but it might be interesting to do it inside the module

**Comment by mifi** [comment]
cool. if you want you can make a PR with the new PropType.
how does your code look like? I don't see how animationData can be undefined if it comes from an import like in your code above.

**Comment by rodbs** [comment]
I've just added the PR
https://github.com/mifi/react-lottie-player/pull/12

Regarding the undefined animationData, I think it was due to the fact I was creating a state variable to load the data into animationData ... I've refactored it; and it looks ok now.

**Comment by mifi** [comment]
Can this be closed now?

**Comment by rodbs** [comment]
Sure!
Thanks.
