### ISSUE TITLE
Warning: ForwardRef: Support for defaultProps will be removed from memo components in a future major release. Use JavaScript default parameters instead.

### ISSUE THREAD

**Issue by mmkal** [mifi/react-lottie-player#100]
I get this console.error message in my component that wraps react-lottie-player:

```
Warning: ForwardRef: Support for defaultProps will be removed from memo components in a future major release. Use JavaScript default parameters instead.
```

version 1.5.4

edit: should mention, everything works fine and it's still useful! just looking to get rid of the error message

**Comment by mifi** [comment]
should be this line:
https://github.com/mifi/react-lottie-player/blob/d730f8b2f053d432a39d414047aa19e419ffb919/src/makeLottiePlayer.js#L210

**Comment by selven** [comment]
I've opened a PR for this, let me know if you want any changes

**Comment by mifi** [comment]
now fixed
