### ISSUE TITLE
Support for React 19

### ISSUE THREAD

**Issue by slevisp** [mifi/react-lottie-player#128]
Hi, 
Really appreciate for this great library. 
Our project is going to update React to 19, I want to know do you guys plan to continue support React 19 as well?

**Comment by mifi** [comment]
I don't see any reason why not. Does it not work on react 19?

**Comment by slevisp** [comment]
Hi mifi, thanks for prompt reply, as I saw in current package.json, the peerDependencies, react is just "^16.0.0 || ^17.0.0 || ^18.0.0"

**Comment by slevisp** [comment]
Created PR for this.
