### ISSUE TITLE
Support for path

### ISSUE THREAD

**Issue by artola** [mifi/react-lottie-player#16]
Lottie-web supports `path` and `animationData`. The first one it is handy to load json as static files (without coding the fetch) and avoid an import or dynamic import (and/or related code splitting), that will lead to bundle animations together to JS, probably not intended for fast load.

https://github.com/airbnb/lottie-web/wiki/loadAnimation-options#path-or-animationdatamandatory-at-least-one

@mifi  What do you think to support this dual way in the API ?

**Comment by mifi** [comment]
I think in general it's good to let the framework (react/webpack/CRA) handle the lazy loading/bundling of chunks as it gives several benefits. I'm not sure if `path` has any benefits over not needing to do an import('/path/to/json').
One benefit I see is that it would allow loading external JSON files from another server, but I don't know if that's very common.

**Comment by artola** [comment]
> I think in general it's good to let the framework (react/webpack/CRA) handle the lazy loading/bundling of chunks as it gives several benefits. I'm not sure if `path` has any benefits over not needing to do an import('/path/to/json').
> One benefit I see is that it would allow loading external JSON files from another server, but I don't know if that's very common.

Right, path will allow to use external servers, or just consume the animations as statics (maybe copied by CopyWebpackPlugin) in place of bundling.

**Comment by Naxes** [comment]
Just chiming in to say this would be useful as we use Contentful with a Gatsby site, which is where the JSON is. We have a setup of content types to construct pages from the CMS, defining what component they should render as. Some of these include animations, hence why they're not simply in the project to be imported. Currently using a fork of `react-lottie` but like the look of this a lot more.

**Comment by artola** [comment]
@mifi 🥇

**Comment by timurguseynov** [comment]
It works 🥇
