### ISSUE TITLE
Play backwards not working without loop

### ISSUE THREAD

**Issue by mikejdegroot** [mifi/react-lottie-player#19]
Hi, 

First of all thanks for creating this package. Much less buggy than the original! I have come across an issue however- 

Play in reverse with the direction=-1 and loop=false does not work. Playing in reverse only seems to work if loop=true. I've taken a look at the live example usage and the same issue happens. I would really like to implement a backwards play without having to do some loop=true/false trickery

Thanks

**Comment by mifi** [comment]
thanks for reporting.
I found the cause of the issue:
https://github.com/airbnb/lottie-web/issues/118#issuecomment-239319708
