### ISSUE TITLE
How to set rendererSetting?

### ISSUE THREAD

**Issue by bit-captain** [mifi/react-lottie-player#2]
In react-lottie we could set it this way
`const defaultOptions = {
    loop: true,
    autoplay: true,
    animationData: lottieChar,
    rendererSettings: {
      preserveAspectRatio: "xMidYMid meet",
    },
  };`
but I don't know how to set it in your lib. I'm a newbie so could be nice if you could provide some example:) .

**Comment by mifi** [comment]
There is a prop
