### ISSUE TITLE
Play on hover

### ISSUE THREAD

**Issue by anubra266** [mifi/react-lottie-player#75]
I can't find a prop to play my animation on hover.

**Comment by mifi** [comment]
react-lotie-player doesnt implement that feature. you need to implement yourself

**Comment by anubra266** [comment]
> react-lotie-player doesnt implement that feature. you need to implement yourself

Thanks @mifi could you point me to some guide on how to do that.

**Comment by mifi** [comment]
I think something like this:
```js
const [playing, setPlaying] = useState(false);

return <Lottie onMouseOver={() => setPlaying(true)} play={playing} />
```
