### ISSUE TITLE
Stop at last frame after completing animation

### ISSUE THREAD

**Issue by rohandey** [mifi/react-lottie-player#92]
@mifi 
I want animation to stop at the last frame once animation completes, I am try this

last_frame = PlayerRef.current.state.instance.totalFrames
PlayerRef.current.goTo(last_frame)

Doesn't seem to work, is there any alternative to this.

**Comment by mifi** [comment]
For this use case i think it’s better to instead use lottie-web directly.
Or you might be able to achieve by setting loop=false

**Comment by rohandey** [comment]
Thank you for the reply loop={false} could not do the trick, will try lottie-web directly now.
